require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.8
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Security/Eval:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'guard']

Style/FrozenStringLiteralComment:
  Enabled: false
