source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'aasm', '~> 5.1.1'
gem 'activeadmin', '~> 2.8.1'
gem 'after_commit_everywhere', '~> 0.1.5'
gem 'aws-sdk-s3', '~> 1.83.0', require: false
gem 'bootsnap', '~> 1.4.8', require: false
gem 'bootstrap-sass', '~> 3.4.1'
gem 'carrierwave', '~> 2.1.0'
gem 'carrierwave-aws', '~> 1.5.0'
gem 'client_side_validations', '~> 17.0.0'
gem 'client_side_validations-simple_form', '~> 11.0.0'
gem 'countries', '~> 3.0.1'
gem 'devise', '~> 4.7.3'
gem 'draper', '~> 4.0.1'
gem 'faker', '~> 2.14.0'
gem 'font-awesome-rails', '~> 4.7.0.5'
gem 'haml-rails', '~> 2.0.1'
gem 'image_processing', '~> 1.2'
gem 'jquery-rails', '~> 4.4.0'
gem 'mini_magick', '~> 4.10.1'
gem 'omniauth', '~> 1.9.1'
gem 'omniauth-facebook', '~> 7.0.0'
gem 'pagy', '~> 3.8.3'
gem 'pg', '~> 1.2.3'
gem 'puma', '~> 3.11'
gem 'rails', '6.0.2'
gem 'sassc-rails', '~> 2.1.2'
gem 'simple_form', '~> 5.0.3'
gem 'turbolinks', '~> 5'
gem 'uglifier', '~> 4.2.0'

group :development, :test do
  gem 'bullet', '~> 6.1.0'
  gem 'dotenv-rails', '~> 2.7.6'
  gem 'factory_bot_rails', '~> 6.1.0'
  gem 'rspec-rails', '~> 4.0.1'
end

group :development do
  gem 'brakeman', '~> 4.10.0'
  gem 'bundler-audit', '~> 0.7.0.1'
  gem 'database_consistency', '~> 0.8.8'
  gem 'guard', '~> 2.16.2'
  gem 'guard-bundler-audit', '~> 0.1.4'
  gem 'guard-livereload', '~> 2.5.2'
  gem 'lefthook', '~> 0.7.2'
  gem 'listen', '~> 3.1.5'
  gem 'rubocop', '~> 0.92.0'
  gem 'rubocop-performance', '~> 1.8.1'
  gem 'rubocop-rails', '~> 2.8.1'
  gem 'rubocop-rspec', '~> 1.43.2'
  gem 'solargraph', '~> 0.39.17'
  gem 'spring', '~> 2.1.1'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara', '~> 3.33.0'
  gem 'capybara-screenshot', '~> 1.0.24'
  gem 'database_cleaner-active_record', '~> 1.8.0'
  gem 'rack_session_access', '~> 0.2.0'
  gem 'rails-controller-testing', '~> 1.0.5'
  gem 'selenium-webdriver', '~> 3.142.7'
  gem 'shoulda-matchers', '~> 4.4.1'
  gem 'simplecov', '~> 0.19.0'
  gem 'site_prism', '~> 3.4.2'
  gem 'webdrivers', '~> 4.4.1'
end
